env:
  node: true 
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  import/extensions: [
    "error",
    {
      "js": "ignorePackages"    
    }
  ],
  no-console: 0
}
